services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile 
    restart: always
    ports:
      - "5000"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.52.0
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
    networks:
      - app-network

  grafana:
    image: grafana/grafana:10.4.2
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

  nginx:
    image: nginx:alpine3.19
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app-network

  # scaler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.scaler
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - web
  #   networks:
  #     - app-network

volumes:
  grafana_data:

networks:
  app-network:
